listaPerguntas = [
    { pergunta: "Qual time não tem mundial ?", alternativas: ["Santos", "Palmeiras", "Corinthians"], resposta: "Palmeiras" },
    { pergunta: "De onde é a invenção do chuveiro elétrico ?", alternativas: ["Brasil", "Argentina", "Paraguai"], resposta: "Brasil" },
    { pergunta: "Quais os países que têm a maior e a menor expectativa de vida do mundo ?", alternativas: ["Estados Unidos e Angola", " Itália e Chade", "Japão e Serra Leoa"], resposta: "Japão e Serra Leoa" },
    { pergunta: "Quais os países que têm a maior e a menor expectativa de vida do mundo ?", alternativas: ["Estados Unidos e Angola", "Itália e Chade", "Japão e Serra Leoa"], resposta: "Japão e Serra Leoa" },
    { pergunta: "Qual é o maior planeta do sistema solar?", alternativas: ["Terra", "Júpiter", "Saturno"], resposta: "Júpiter" },
    { pergunta: "Qual país tem a maior população do mundo?", alternativas: ["Índia", "Estados Unidos", "China"], resposta: "Índia" },
    { pergunta: "Em que continente fica o Deserto do Saara?", alternativas: ["África", "Ásia", "América"], resposta: "África" },
    { pergunta: "Qual é o menor osso do corpo humano?", alternativas: ["Fêmur", "Esterno", "Estribo"], resposta: "Estribo" },
    { pergunta: "Quem foi o primeiro homem a pisar na Lua?", alternativas: ["Buzz Aldrin", "Neil Armstrong", "Yuri Gagarin"], resposta: "Neil Armstrong" },
    { pergunta: "Qual é a capital do Canadá?", alternativas: ["Toronto", "Montreal", "Ottawa"], resposta: "Ottawa" },
    { pergunta: "Qual é o idioma oficial da Argentina?", alternativas: ["Português", "Espanhol", "Italiano"], resposta: "Espanhol" },
    { pergunta: "Quantos elementos há na tabela periódica atualmente (2025)?", alternativas: ["118", "115", "120"], resposta: "118" },
    { pergunta: "Quem escreveu 'Dom Quixote'?", alternativas: ["William Shakespeare", "Machado de Assis", "Miguel de Cervantes"], resposta: "Miguel de Cervantes" },
    { pergunta: "Qual é o maior oceano do mundo?", alternativas: ["Atlântico", "Índico", "Pacífico"], resposta: "Pacífico" },
    { pergunta: "Que animal é símbolo da paz?", alternativas: ["Águia", "Pomba", "Cisne"], resposta: "Pomba" },
    { pergunta: "Qual é o país mais novo do mundo (2025)?", alternativas: ["Kosovo", "Sudão do Sul", "Timor-Leste"], resposta: "Sudão do Sul" },
    { pergunta: "Qual é o metal mais leve da tabela periódica?", alternativas: ["Alumínio", "Lítio", "Sódio"], resposta: "Lítio" },
    { pergunta: "Em que ano aconteceu a Revolução Francesa?", alternativas: ["1789", "1804", "1776"], resposta: "1789" },
    { pergunta: "Qual foi o primeiro país a conquistar uma Copa do Mundo?", alternativas: ["Brasil", "Uruguai", "Alemanha"], resposta: "Uruguai" },
    { pergunta: "Qual é a capital da Austrália?", alternativas: ["Sydney", "Melbourne", "Camberra"], resposta: "Camberra" },
    { pergunta: "Qual é o rio mais longo do mundo?", alternativas: ["Nilo", "Amazonas", "Yangtzé"], resposta: "Amazonas" },
    { pergunta: "Quem pintou a Mona Lisa?", alternativas: ["Leonardo da Vinci", "Michelangelo", "Van Gogh"], resposta: "Leonardo da Vinci" },
    { pergunta: "O que é fotossíntese?", alternativas: ["Respiração celular", "Processo de produção de energia solar", "Processo de produção de alimento pelas plantas"], resposta: "Processo de produção de alimento pelas plantas" },
    { pergunta: "Qual é o planeta mais próximo do Sol?", alternativas: ["Vênus", "Mercúrio", "Marte"], resposta: "Mercúrio" },
    { pergunta: "Em que país nasceu Albert Einstein?", alternativas: ["Estados Unidos", "Alemanha", "Suíça"], resposta: "Alemanha" },
    { pergunta: "Qual é a moeda oficial do Japão?", alternativas: ["Yuan", "Yene", "Won"], resposta: "Yene" },
    { pergunta: "Qual foi o primeiro país a abolir a escravidão?", alternativas: ["Brasil", "Inglaterra", "Haiti"], resposta: "Haiti" },
    { pergunta: "Quem foi o criador da teoria da gravidade?", alternativas: ["Einstein", "Galileu", "Newton"], resposta: "Newton" },
    { pergunta: "O que mede a escala Richter?", alternativas: ["Velocidade dos ventos", "Temperatura", "Magnitude de terremotos"], resposta: "Magnitude de terremotos" },
    { pergunta: "Qual é o país com maior número de vulcões ativos?", alternativas: ["Indonésia", "Japão", "Itália"], resposta: "Indonésia" },
    { pergunta: "Qual foi a primeira capital do Brasil?", alternativas: ["Salvador", "Recife", "Rio de Janeiro"], resposta: "Salvador" },
    { pergunta: "Qual o principal gás do efeito estufa?", alternativas: ["Oxigênio", "Metano", "Dióxido de carbono"], resposta: "Dióxido de carbono" },
    { pergunta: "Qual a cor que representa o luto na maioria dos países ocidentais?", alternativas: ["Preto", "Cinza", "Branco"], resposta: "Preto" },
    { pergunta: "Quem escreveu 'Os Lusíadas'?", alternativas: ["Camões", "Fernando Pessoa", "Eça de Queirós"], resposta: "Camões" },
    { pergunta: "Qual é o maior arquipélago do mundo?", alternativas: ["Filipinas", "Japão", "Indonésia"], resposta: "Indonésia" },
    { pergunta: "Quantos lados tem um octógono?", alternativas: ["Seis", "Oito", "Dez"], resposta: "Oito" },
    { pergunta: "Qual é o animal mais rápido do mundo?", alternativas: ["Guepardo", "Falcão-peregrino", "Leopardo"], resposta: "Falcão-peregrino" },
    { pergunta: "Quem foi o primeiro presidente do Brasil?", alternativas: ["Deodoro da Fonseca", "Getúlio Vargas", "Dom Pedro II"], resposta: "Deodoro da Fonseca" },
    { pergunta: "Qual é o maior país da América do Sul?", alternativas: ["Argentina", "Brasil", "Colômbia"], resposta: "Brasil" },
    { pergunta: "Em que continente fica o país da Geórgia?", alternativas: ["Ásia", "Europa", "Ambos"], resposta: "Ambos" },
    { pergunta: "Qual é o maior órgão do corpo humano?", alternativas: ["Fígado", "Pele", "Cérebro"], resposta: "Pele" },
    { pergunta: "Qual é a montanha mais alta do mundo?", alternativas: ["Everest", "K2", "Makalu"], resposta: "Everest" },
    { pergunta: "Que país é famoso por inventar o papel?", alternativas: ["Egito", "Grécia", "China"], resposta: "China" },
    { pergunta: "Quantos planetas há no sistema solar?", alternativas: ["8", "9", "10"], resposta: "8" },
    { pergunta: "Quem é o autor de 'Romeu e Julieta'?", alternativas: ["Shakespeare", "Charles Dickens", "Victor Hugo"], resposta: "Shakespeare" },
    { pergunta: "Qual é o ponto mais profundo dos oceanos?", alternativas: ["Fossa de Java", "Fossa das Marianas", "Fossa do Atlântico"], resposta: "Fossa das Marianas" },
    { pergunta: "Qual país tem a maior extensão territorial do mundo?", alternativas: ["Canadá", "Estados Unidos", "Rússia"], resposta: "Rússia" },
    { pergunta: "Qual esporte é conhecido como 'o esporte bretão'?", alternativas: ["Críquete", "Tênis", "Futebol"], resposta: "Futebol" },
    { pergunta: "Quem descobriu o Brasil?", alternativas: ["Pedro Álvares Cabral", "Cristóvão Colombo", "Vasco da Gama"], resposta: "Pedro Álvares Cabral" },
]